### ISSUE TITLE
Setup a CD pipeline from a custom running Linode server

### ISSUE THREAD

**Issue by kuroji-fusky** [openfurs/searchpets#13]
Manual deployment is pain.

**Comment by thatITfox** [comment]
how about a bash file and gh actions?

**Comment by skepfusky** [comment]
@thatITfox I guess that would work if you can figure things up properly lol

**Comment by thatITfox** [comment]
yeah XD, ill get on it as soon as i can

**Comment by skepfusky** [comment]
Awesome👌

**Comment by skepfusky** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Searchpets - Future Updates](https://trello.com/c/c9AQbYJm/3-searchpets-future-updates)
